# Generated by Django 6.0.6 on 2026-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0002_image_notes_seriesreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='patient_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='image',
            name='patient_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='image',
            name='test_code',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
