# Generated by Django 6.0.6 on 2026-07-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotate", "0003_image_patient_code_image_patient_id_image_test_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seriesreview",
            name="patient_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="seriesreview",
            name="patient_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="seriesreview",
            name="test_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="seriesreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="seriesreview",
            constraint=models.UniqueConstraint(
                fields=("user", "patient_id", "patient_code", "test_code"),
                name="unique_series_review_per_user",
            ),
        ),
    ]
